# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict

- repo: https://github.com/pycqa/isort
  rev: 5.11.4
  hooks:
    - id: isort
      args: [--profile, black, --line-length=120]

- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: [--max-line-length=120]

- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
      args: [--line-length=120]

- repo: local
  hooks:
    - id: export-dev-requirements
      name: Export DEV requirements.txt
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --with dev --output requirements/dev.txt
      files: ^(pyproject.toml|poetry.lock)$
    - id: export-prod-requirements
      name: Export PROD requirements.txt
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes --output requirements/prod.txt
      files: ^(pyproject.toml|poetry.lock)$
